# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
# permalink:        pretty
permalink: "/:title"
# Setup
title:            Ismail Kalimi
tagline:
description:
url:              http://ikalimi.com

author:
  name:           'Ismail Kalimi'
  url:            https://ikalimi.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ismk